### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by gabrielegranello** [theopensystemslab/fairhold-dashboard#132]
<img width="1200" alt="Screenshot 2024-10-25 at 10 06 07" src="https://github.com/user-attachments/assets/7cb72359-1576-41fb-a878-f8f8b9f59e56">

**Comment by gabrielegranello** [comment]
This is due to :
ERROR: API -  Service error: Unable to generate household. Message: Data error: Unable get get itl3 for postcode district SE17

**Comment by zz-hh-aa** [comment]
Interesting--are you on `main`? I encountered this error at some point yesterday on a feature branch (I think `oz/maintenance`) but then resolved it. I've just pulled `main` and run `build` and `dev` and have not encountered any issues.

**Comment by gabrielegranello** [comment]
Hi @zz-hh-aa yes I still do encounter it on main. How did you manage to solve it?

**Comment by gabrielegranello** [comment]
Did you run : git pull 
to run in on the most updated version of main?

**Comment by gabrielegranello** [comment]
This even more confusing. I swear I am on main and run git pull. 
So that if I run git status, I receive the message everything up to date.

npm run build works. If I do npm run dev and interact with the form then I get the error above

**Comment by zz-hh-aa** [comment]
Wonder if it's worth deleting and re-cloning the repo (and re-installing dependencies)?

**Comment by gabrielegranello** [comment]
I am going to scream. I have deleted the repo and re-cloned it. Still.Same.Error.

**Comment by gabrielegranello** [comment]
SOLVED!
